version: '3.3'

networks:
  teacher-service-network:
    driver: bridge

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'schooldb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  wiremock:
    build: ./wiremock-docker
    image: teacher-service/wiremock:latest
    container_name: teacher-service-wiremock
    environment:
      - WIREMOCK_VERSION=2.24.1
    ports:
      - 9090:9090
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9090"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./wiremock-mappings:/home/wiremock/mappings
    networks:
      - teacher-service-network
volumes:
  my-db:
  